[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.6.1"
vek = "0.15.9"